Repository nbcamp-react/movie-app, pull requests merged in 2023-10, with the labels that each got.

#7 chore: 영화 API popular로 변경
  index.html
  src/movie.js
Labels: 수정

#8 feat: 영화 정렬 기능 구현
  index.html
  src/constants.js
  src/main.js
  src/movie.js
Labels: UI, 기능

#10 chore: 메인 페이지 배너 이미지 변경 (#9)
  assets/banner.jpg
Labels: UI

#12 feat: 상세페이지 이동 및 기능 구현 (#3)
  .prettierrc
  UIdetail.html
  index.html
  src/detail.js
  src/movie.js
Labels: 기능

#13 feat: 상세페이지 화면구현 (#5)
  UIdetail.html
  index.html
Labels: 기능

#14 feat: 영화 제목과 평점으로 정렬 기능 추가
  index.html
  src/constants.js
  src/main.js
  src/movie.js
  src/sort.js
  style/style.css
Labels: UI, 기능

#15 feat: 상세페이지 화면구현 (#5)
  src/detail.js
  style/style-detail.css
Labels: UI

#17 feat: 영화 상세 페이지 리뷰 (#16)
  UIdetail.html
  src/comment_login.js
  style/style-detail.css
Labels: UI, 기능

#19 fix: UIindex.html script 파일 누락
  UIdetail.html
  style/style-detail.css
Labels: 버그

#20 feat: 영화 검색 시 유효성 검사 (#4)
  src/main.js
  src/search.js
Labels: 기능

#23 chore: 메인 CSS 수정 및 타이틀 링크 삽입 (#22)
  index.html
  src/movie.js
  style/style.css
Labels: UI, 기능

#24 feat: 영화 평점 기준으로 필터링 적용
  src/sort.js
Labels: 기능

#27 feat: main 브랜치 배포 전 기능 검사, 불필요한 코드 삭제
  README.md
  UIdetail.html
  index.html
  src/search.js
Labels: 문서, 수정, 기능

#28 Feature/searchvalidation
  index.html
  src/search.js
Labels: 기능

#29 Feature/u idetail
  UIdetail.html
  style/style-detail.css
Labels: UI

#30 feat: 검색 결과 후 필터링 기능 개선 (#21)
  src/search.js
  src/sort.js
  style/style.css
Labels: 기능

#31 chore: 메인 영화 카드 장르 표시 및 UI 수정 (#26)
  README.md
  src/constants.js
  src/detail.js
  src/movie.js
  style/style.css
Labels: UI, 수정

#34 [feature/comment] 기능 구현 댓글 로그인 #32
  .vscode/settings.json
  UIdetail.html
  src/comment_login.js
Labels: 기능

#35 Feature/u idetail #5 상세페이지 홈버튼 기능추가
  UIdetail.html
  style/style-detail.css
Labels: UI, 수정, 기능

#38 chore: 영화 이미지 및 상세정보 정렬 수정 (#37)
  UIdetail.html
  src/detail.js
  style/style-detail.css
Labels: UI, 수정

#40 chore: 상세페이지 댓글 박스 생성 및 정렬 UI 수정 (#39)
  UIdetail.html
  style/reset.css
  style/style-detail.css
Labels: UI, 수정

#41 feat: 영화 장르 필터 추가
  index.html
  src/sort.js
  style/style.css
Labels: UI, 기능

#43 feat: v1.1.0 배포
  .vscode/settings.json
  README.md
  UIdetail.html
  src/movie.js
  src/sort.js
  style/style-detail.css
Labels: 배포

#44 feat: v1.1.0 배포
  .prettierrc
  README.md
  UIdetail.html
  assets/banner.jpg
  index.html
  src/comment_login.js
  src/constants.js
  src/detail.js
  src/main.js
  src/movie.js
  src/search.js
  src/sort.js
  style/reset.css
  style/style-detail.css
  style/style.css
Labels: 배포
